v2.1.3_a4

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.3_a2
+TCPROXY_COMMIT=v2.1.3_a4
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.1.3
 #/heads/branch or /tags/version for releases
@@ -43,7 +43,7 @@ for cmd in bash sudo whoami id uname cat md5sum awk grep head readlink pwd chmod
     fi
 done
 if ! command -v curl &> /dev/null && ! command -v wget &> /dev/null; then
-    echo "[ERROR] Either 'curl' or 'wget' is required but neither is installed."
+    echo "[ERROR] Both 'curl' and 'wget' are required."
     MISSING_DEPS=1
 fi
 if [[ $MISSING_DEPS -eq 1 ]]; then
@@ -440,9 +440,9 @@ test_VM_mount() {
 
 check_smb_share() {
     VM_SMB_CHECK=0
-    if [[ -n $TC_DISK_USB ]]; then smbclient //127.0.0.1/$TC_DISK_USB -U root%$TC_PASSWORD --port=50445 -c 'exit'; if [[ $? -ne 0 ]]; then echo "Failed to access $TC_DISK_USB"; VM_SMB_CHECK=$?; else echo "$TC_DISK_USB in VM OK"; fi ; fi
-    if [[ -n $TC_USER ]]; then smbclient //127.0.0.1/$TC_USER -U root%$TC_PASSWORD --port=50445 -c 'exit'; if [[ $? -ne 0 ]]; then echo "Failed to access $TC_USER"; VM_SMB_CHECK=$?; else echo "$TC_USER in VM OK"; fi ; fi
-    if [[ -n $TC_DISK ]]; then smbclient //127.0.0.1/$TC_DISK -U root%$TC_PASSWORD --port=50445 -c 'exit'; if [[ $? -ne 0 ]]; then echo "Failed to access $TC_DISK"; VM_SMB_CHECK=$?; else echo "$TC_DISK in VM OK"; fi ; fi
+    if [[ -n $TC_DISK_USB ]]; then smbclient //127.0.0.1/$TC_DISK_USB -U root%$TC_PASSWORD --port=50445 -c 'exit'; VM_SMB_CHECK=$?; if [[ $? -ne 0 ]]; then echo "[ERROR] Failed to access $TC_DISK_USB"; else echo "Mount [$TC_DISK_USB] in VM OK"; fi ; fi
+    if [[ -n $TC_USER ]]; then smbclient //127.0.0.1/$TC_USER -U root%$TC_PASSWORD --port=50445 -c 'exit'; VM_SMB_CHECK=$?; if [[ $? -ne 0 ]]; then echo "[ERROR] Failed to access $TC_USER"; else echo "Mount [$TC_USER] in VM OK"; fi ; fi
+    if [[ -n $TC_DISK ]]; then smbclient //127.0.0.1/$TC_DISK -U root%$TC_PASSWORD --port=50445 -c 'exit'; VM_SMB_CHECK=$?; if [[ $? -ne 0 ]]; then echo "[ERROR] Failed to access $TC_DISK"; else echo "Mount [$TC_DISK] in VM OK"; fi ; fi
     return $VM_SMB_CHECK
 }
 
@@ -453,7 +453,7 @@ tcproxy_up() {
     REBOOT_COUNT_VM_UP=5
     logm "Checking VM status..."
     # if ! pgrep -f "mac=02:D2:46:5B:4E:84" > /dev/null 2>&1; then
-    if ! pgrep -f "mac=02:D2:46:5B:4E:84"; then
+    if ! pgrep -f "mac=02:D2:46:5B:4E:84" >/dev/null 2>&1; then
         load_VM
         check_VM_status
     fi
@@ -469,6 +469,7 @@ tcproxy_up() {
             sleep 10
             load_VM
         fi
+        test_VM_mount
         logm "[INFO] Failed to access VM samba share. Waiting 180 seconds before next attempt. Attempt $RETRY_COUNT_UP/$MAX_RETRIES_UP."
         sleep $RETRY_INTERVAL_UP
     done
@@ -489,15 +490,16 @@ mount_routine() {
         RETRY_COUNT_M=0
         while [ $RETRY_COUNT_M -lt $MAX_RETRIES_M ]; do
             # echo "mountpoint selected: $MOUNT_POINT_M"
-            if mountpoint -q /srv/tcproxy/$MOUNT_POINT_M; then logm "/srv/tcproxy/$MOUNT_POINT_M mounted and accessible"; break; else
-                RESPONSE_M=$(logc sudo mount -t cifs //127.0.0.1/$MOUNT_POINT_M /srv/tcproxy/$MOUNT_POINT_M -o username=root,password="$TC_PASSWORD",rw,iocharset=utf8,vers=3.0,nofail,port=50445,uid=$PUID,gid=$PGID 2>&1)
-                if [ $? -eq 0 ]; then
+            if mountpoint /srv/tcproxy/$MOUNT_POINT_M >/dev/null 2>&1; then 
+                logm "/srv/tcproxy/$MOUNT_POINT_M mounted and accessible"
+                break
+            else
+                logsc sudo mount -t cifs //127.0.0.1/$MOUNT_POINT_M /srv/tcproxy/$MOUNT_POINT_M -o username=root,password="$TC_PASSWORD",rw,iocharset=utf8,vers=3.0,nofail,port=50445,uid=$PUID,gid=$PGID 2>&1
+                if [ $LOGSC_OUTPUT -eq 0 ]; then
                     logm "/srv/tcproxy/$MOUNT_POINT_M mounted and accessible"
                     break
                 else
-                    echo $?
-                    echo "$RESPONSE_M"
-                    logm "Failed to mount $MOUNT_POINT_M. $RESPONSE_M. Check system and retry."
+                    logm "[ERROR: $LOGSC_OUTPUT] failed to mount [$MOUNT_POINT_M]: $LOGSC_COMMAND. Check system and retry."
                     sleep 5
                 fi
             fi
@@ -650,7 +652,7 @@ help_menu() {
     echo "  --update-check            check for updates from project server 
   --update                  requests update from project server and attempts local upgrade
   --remote-log              Sends last 100 log lines to debug server
-  --enable-service          install systemd startup service"; fi
+  --enable-service          (beta) installs systemd startup service"; fi
   echo "  --disable-service         stops and removes systemd startup service
   --uninstall               unmounts /srv/tcproxy and poweroff to VM and stops and removes system service
 
@@ -700,14 +702,23 @@ logc() {
     LOG_MESSAGE="$(date +"%Y%m%d_%H:%M:%S"): $0 $*"
     LOG_MESSAGE_TIMESTAMP="$(date +"%Y%m%d_%H:%M:%S"): $LOG_MESSAGE"
     echo $LOG_MESSAGE_TIMESTAMP >> "$LOG_FILE"
-    eval "$@ 2>&1 | tee -a \"$LOG_FILE\""
+    # eval "$@ 2>&1 | tee -a \"$LOG_FILE\""
+    LOGC_COMMAND=$("$@" 2>&1)
+    LOGC_OUTPUT=$?
+    echo "$LOGC_COMMAND" | tee -a "$LOG_FILE"
+    return $LOGC_OUTPUT
 }
 
 logsc() {
     LOG_MESSAGE="$(date +"%Y%m%d_%H:%M:%S"): $0 $@"
     LOG_MESSAGE_TIMESTAMP="$(date +"%Y%m%d_%H:%M:%S"): $LOG_MESSAGE"
     echo $LOG_MESSAGE_TIMESTAMP >> "$LOG_FILE"
-    "$@" >> "$LOG_FILE" 2>&1
+    # "$@" >> "$LOG_FILE" 2>&1
+    # return $?
+    LOGSC_COMMAND=$("$@" 2>&1)
+    LOGSC_OUTPUT=$?
+    echo "$LOGSC_COMMAND" >> "$LOG_FILE"
+    return $LOGSC_OUTPUT
 }
 
 logm() {
@@ -758,7 +769,6 @@ if [[ $1 == "--startup-boot" ]]; then
     tcproxy_up
     exit 0
 fi
-#if [ -n "$INVOCATION_ID" ]; then logsc tcproxy_up; exit 0; fi
 if sudo -n true 2>/dev/null; then : # echo "Sudo session is active and validated."
 else
     SUDO_OUTPUT=$(sudo -v 2>&1)
@@ -802,11 +812,6 @@ $TCPROXY_PATH
 "
     curl --connect-timeout 5 --max-time 10 -s -o /dev/null -w "%{http_code}" -X POST -d "$UNIQUE_ID;$ARCH;$TCPROXY_COMMIT;ST=$STATS;uninstalled" "http://$L1.$L2.$L3.$L4:$L5" >/dev/null 2>&1
     footer
-# elif [[ $1 == "" ]] && [[ ! $TC_PASSWORD == "" ]]; then
-#     DESCR_COM="no argument. Defaulting to [ ./tcproxy --up ]"; header
-#     echo "Loading and mounting VM..."
-#     tcproxy_up
-#     footer
 elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
     DESCR_COM="Installing..."; header
     if [ -v BETA ]; then
@@ -849,11 +854,6 @@ This is intended for DEV testing ONLY."
         echo "[ERROR] Nothing to mount. At least one input among User, DISK or USB Disk is required. Process aborted."
         exit 1
     fi
-    # whiptail --title "Mount at Startup" --yesno "Do you want to enable mount at startup?" 8 60
-    # STARTUP_MOUNT_Q=$?
-    # if [ $STARTUP_MOUNT_Q -eq 0 ]; then
-    #     STARTUP_MOUNT="Y"
-    # fi
     github_download
     deflating_vm
     umount_srv_tcproxy
@@ -866,12 +866,6 @@ This is intended for DEV testing ONLY."
     test_VM_mount
     tcproxy_up
     save_ENVs_to_file
-    # if [[ "$STARTUP_MOUNT" =~ ^[Yy]$ ]]; then
-    #     tcproxy_systemd_setup
-    #     remove_system_service
-    #     install_system_service
-    # fi
-    # save_ENVs_to_file
     post_install_cleanup
     logsc sudo rm .tcproxy-uninstalled
     logm "Installation completed in folder tcproxy/"
