v2.0.0_beta1.147

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_VERSION=v2.0.0_beta1.146
+TCPROXY_VERSION=v2.0.0_beta1.147
 TCPROXY_BRANCH=v2.0.0
 
 logc() {
@@ -434,27 +434,30 @@ WantedBy=multi-user.target" > "$TCP_SERVICE_TEMP_FILE"
 }
         
 remove_system_service() {
-        logm "Scanning for previously installed daemons..."
-        if [[ -f /etc/systemd/system/time-capsule-proxy.service ]]; then
-            logsc sudo systemctl stop time-capsule-proxy.service
-            logsc sudo systemctl disable time-capsule-proxy.service
-            logsc sudo rm /etc/systemd/system/time-capsule-proxy.service
-        fi
-        if [[ -f /etc/systemd/system/tcproxy.service ]]; then
-            logsc sudo systemctl stop tcproxy.service
-            logsc sudo systemctl disable tcproxy.service
-            logsc sudo rm /etc/systemd/system/tcproxy.service
-        fi
+    logm "Scanning for previously installed daemons..."
+    if [[ -f /etc/systemd/system/time-capsule-proxy.service ]]; then
+        logsc sudo systemctl stop time-capsule-proxy.service
+        logsc sudo systemctl disable time-capsule-proxy.service
+        logsc sudo rm /etc/systemd/system/time-capsule-proxy.service
+    fi
+    if [[ -f /etc/systemd/system/tcproxy.service ]]; then
+        logsc sudo systemctl stop tcproxy.service
+        logsc sudo systemctl disable tcproxy.service
+        logsc sudo rm /etc/systemd/system/tcproxy.service
+    fi
 }
 
 install_system_service() {
-        logsc sudo cp $TCP_SERVICE_TEMP_FILE $TIME_CAPSULE_PROXY_SERVICE
-        logsc sudo systemctl daemon-reload
-        logsc sudo systemctl enable tcproxy.service
-        if sudo systemctl start tcproxy.service; then
-            logm "Service enabled at boot."
-        else logm "[ERROR] Failed to start tcproxy.service - Error code $?"
-        fi
+    logsc sudo cp $TCP_SERVICE_TEMP_FILE $TIME_CAPSULE_PROXY_SERVICE
+    logsc sudo systemctl daemon-reload
+    logsc sudo systemctl enable tcproxy.service
+    logsc sudo systemctl start tcproxy.service
+    logsc sudo systemctl is-active --quiet tcproxy.service
+    if [ $? -eq 0 ]; then
+        logm "Service enabled at boot."
+    else
+        logm "[ERROR] Failed to start tcproxy.service - Error code $?"
+    fi
 }
 
 ssh_vm() {
