v2.0.5-c6

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.0.5-c5
+TCPROXY_COMMIT=v2.0.5-c6
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.0.4
 #/heads/branch or /tags/version for releases
@@ -745,12 +745,11 @@ elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
     DESCR_COM="Installing..."; header
     define_tcproxy_env_vars
     check_system_requirements
-    INSTALL_CONFIRMATION=$(whiptail --title "Installation Confirmation" \
-                                    --yesno "Close any app or terminal window using /srv/tcproxy before continuing.\n\nDo you want to continue with the installation?" \
-                                    15 60 3>&1 1>&2 2>&3)
-    if [ $? -ne 0 ]; then
-        echo "Input = $? [INFO] Process Aborted. No change has been performed."
-        exit 1
+    whiptail --title "test222" --yesno "Close any app or terminal window using /srv/tcproxy before continuing.\n\nDo you want to continue with the installation?" 15 60
+    INSTALL_CONFIRMATION=$?
+    if [ $INSTALL_CONFIRMATION -ne 0 ]; then
+        echo "Input = $INSTALL_CONFIRMATION [INFO] Process Aborted. No change has been performed."
+        prompt_user_inputs
     fi
     TC_IP=$(whiptail --title "Time Capsule IPv4" --inputbox "Enter Time Capsule IPv4 (e.g., 192.168.1.10):" 8 60 "" 3>&1 1>&2 2>&3)
     if [ -z "$TC_IP" ]; then
@@ -777,6 +776,7 @@ elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
     fi
     echo "Install conf: $INSTALL_CONFIRMATION"
     if [ -z "$INSTALL_CONFIRMATION" ]; then 
+    echo "end if to prompt user"
         prompt_user_inputs
     fi
     github_download
