v2.0.0_beta1.234

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_VERSION=v2.0.0_beta1.233
+TCPROXY_VERSION=v2.0.0_beta1.234
 TCPROXY_BRANCH=v2.0.0
 
 define_tcproxy_env_vars() {
@@ -255,7 +255,7 @@ testing_ssh_premission_requirements() {
 prompt_user_inputs() {
 echo "GNU tcproxy $TCPROXY_VERSION - Mount Time Capsule / AirPort Extreme on kernels 5.15 or above.
 
-Close any app or terminal window using /srv/tc-proxy before continuing."
+Close any app or terminal window using /srv/tcproxy before continuing."
 read -p "[INPUT] Continue? (y/N): " CONFIRM_INSTALL
 
     if [[ "$CONFIRM_INSTALL" =~ ^[Yy]$ ]]; then
@@ -296,20 +296,20 @@ deflating_vm() {
 }
 
 unmount_srv_tcproxy() {
-    if sudo umount /srv/tc-proxy >/dev/null 2>&1; then
-        logsm "Unmount of /srv/tc-proxy successful..."
+    if sudo umount /srv/tcproxy >/dev/null 2>&1; then
+        logsm "Unmount of /srv/tcproxy successful..."
     else
         sleep 5 
-        if  mountpoint -q "/srv/tc-proxy"; then
-            if sudo umount -f /srv/tc-proxy >/dev/null 2>&1; then
-                logm "[INFO] forced unmount of /srv/tc-proxy successful..."
+        if  mountpoint -q "/srv/tcproxy"; then
+            if sudo umount -f /srv/tcproxy >/dev/null 2>&1; then
+                logm "[INFO] forced unmount of /srv/tcproxy successful..."
             else
                 EXIT_CODE=$?
-                logm "[ERROR $EXIT_CODE] Cannot unmount /srv/tc-proxy. Please check your system and run tcproxy -i again."
+                logm "[ERROR $EXIT_CODE] Cannot unmount /srv/tcproxy. Please check your system and run tcproxy -i again."
                 exit 1
             fi
         else
-            logsm "Late unmount of /srv/tc-proxy successful..."
+            logsm "Late unmount of /srv/tcproxy successful..."
         fi
     fi
 }
@@ -379,7 +379,7 @@ check_VM_status() {
 }
 
 creating_mountpoint_folder() {
-    logsc sudo mkdir -p /srv/tc-proxy
+    logsc sudo mkdir -p /srv/tcproxy
 }
 
 provision_VM() {
@@ -447,12 +447,12 @@ tcproxy_up() {
         fi
     done
     # Verify host mount
-    if ! mountpoint -q /srv/tc-proxy >/dev/null 2>&1; then
-        logm "Remounting /srv/tc-proxy..."
+    if ! mountpoint -q /srv/tcproxy >/dev/null 2>&1; then
+        logm "Remounting /srv/tcproxy..."
         unmount_srv_tcproxy
-        logsc sudo mount -t cifs //127.0.0.1/tc-proxy /srv/tc-proxy/ -o password="$TC_PASSWORD""$TC_FSTAB_USER",rw,uid="$PUID",iocharset=utf8,vers=3.0,nofail,file_mode=0775,dir_mode=0775,port=50445
+        logsc sudo mount -t cifs //127.0.0.1/tc-proxy /srv/tcproxy/ -o password="$TC_PASSWORD""$TC_FSTAB_USER",rw,uid="$PUID",iocharset=utf8,vers=3.0,nofail,file_mode=0775,dir_mode=0775,port=50445
     fi
-    logm "/srv/tc-proxy mounted and accessible"
+    logm "/srv/tcproxy mounted and accessible"
     return 0
 }
 
