v2.1.2-d3

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,7 +1,7 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.2-d2
-TCPROXY_BRANCH=/heads/beta
+TCPROXY_COMMIT=v2.1.2-d3
+TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.1.2
 #/heads/branch or /tags/version for releases
 USER=$(whoami)
@@ -306,31 +306,44 @@ stopping_VM() {
 }
 
 load_VM() {
-    if [[ $ARCH == x86_64* ]]; then
-        sudo qemu-system-x86_64 \
-        -M q35,accel=kvm \
-        -cpu host \
-        -m 256 \
-        -boot order=c \
-        -drive file=$TCPROXY_PATH/data.img,format=qcow2,if=virtio \
-        -netdev user,id=net0,hostfwd=tcp::50022-:22,hostfwd=tcp::50445-:445 \
-        -device virtio-net,netdev=net0,mac=$(cat $TCPROXY_PATH/qemu.mac) \
-        -serial file:$TCPROXY_PATH/.vm-serial-file \
-        -daemonize \
-        -display none
-    elif [[ $ARCH == aarch64* ]]; then
-        sudo qemu-system-aarch64 \
-        -M virt,accel=kvm \
-        -cpu host \
-        -m 256 \
-        -drive file=$TCPROXY_PATH/data.img,format=qcow2,if=virtio \
-        -bios $TCPROXY_PATH/uefi.rom \
-        -device virtio-net-device,netdev=net0,mac=$(cat $TCPROXY_PATH/qemu.mac) \
-        -netdev user,id=net0,hostfwd=tcp::50022-:22,hostfwd=tcp::50445-:445 \
-        -serial file:$TCPROXY_PATH/.vm-serial-file \
-        -daemonize \
-        -display none
-    fi
+    MAX_RETRIES_VM_UP=10
+    RETRY_INTERVAL_VM_UP=15
+    RETRY_COUNT_VM_UP=0
+    while ! pgrep -f "mac=02:D2:46:5B:4E:84" >/dev/null 2>&1; do
+        RETRY_COUNT_VM_UP=$((RETRY_COUNT_VM_ST + 1))
+        if [ $RETRY_COUNT_VM_UP -ge $MAX_RETRIES_VM_UP ]; then
+            logm "[ERROR] Max retries for load_VM reached. Exiting..."
+            exit 1
+        fi
+        logm "VM down... attempting to restart..."
+        if [[ $ARCH == x86_64* ]]; then
+            sudo qemu-system-x86_64 \
+            -M q35,accel=kvm \
+            -cpu host \
+            -m 256 \
+            -boot order=c \
+            -drive file=$TCPROXY_PATH/data.img,format=qcow2,if=virtio \
+            -netdev user,id=net0,hostfwd=tcp::50022-:22,hostfwd=tcp::50445-:445 \
+            -device virtio-net,netdev=net0,mac=$(cat $TCPROXY_PATH/qemu.mac) \
+            -serial file:$TCPROXY_PATH/.vm-serial-file \
+            -daemonize \
+            -display none
+        elif [[ $ARCH == aarch64* ]]; then
+            sudo qemu-system-aarch64 \
+            -M virt,accel=kvm \
+            -cpu host \
+            -m 256 \
+            -drive file=$TCPROXY_PATH/data.img,format=qcow2,if=virtio \
+            -bios $TCPROXY_PATH/uefi.rom \
+            -device virtio-net-device,netdev=net0,mac=$(cat $TCPROXY_PATH/qemu.mac) \
+            -netdev user,id=net0,hostfwd=tcp::50022-:22,hostfwd=tcp::50445-:445 \
+            -serial file:$TCPROXY_PATH/.vm-serial-file \
+            -daemonize \
+            -display none
+        fi
+        sleep $RETRY_INTERVAL_VM_UP
+    done
+    logm "VM launched..."
 }
 
 check_VM_status() {
