v2.1.1-b9

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.1-b8
+TCPROXY_COMMIT=v2.1.1-b9
 TCPROXY_BRANCH=/heads/pre-dev
 TCPROXY_RELEASE=v2.1.0
 #/heads/branch or /tags/version for releases
@@ -831,7 +831,6 @@ elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
     check_system_requirements
     whiptail --title "tcproxy $TCPROXY_COMMIT installation GUI" --yesno "Close any app or terminal window using /srv/tcproxy before continuing.\n\nDo you want to continue?" 15 60
     INSTALL_CONFIRMATION=$?
-    echo "INSTALL_CONFIRMATION: $INSTALL_CONFIRMATION"
     if [ $INSTALL_CONFIRMATION -ne 0 ]; then
         if [[ $WEB_INSTALL != "TRUE" ]]; then prompt_user_inputs; else echo "[INFO] GUI Process Aborted. tcproxy has not been installed."; exit 1; fi
     fi
@@ -846,12 +845,12 @@ elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
         echo "[ERROR] PASSWORD is required. Process aborted."
         exit 1
     fi
-    TC_DISK=$(whiptail --title "Time Capsule DISK name" --inputbox "Enter Time Capsule DISK name (e.g., Data):" 8 60 "" 3>&1 1>&2 2>&3)
-    # if [ -z "$TC_DISK" ]; then
-    #     echo "[ERROR] DISK name is required. Process aborted."
-    #     exit 1
-    # fi
+    TC_DISK=$(whiptail --title "Time Capsule DISK name" --inputbox "Enter Time Capsule DISK name e.g., Data (optional):" 8 60 "" 3>&1 1>&2 2>&3)
     TC_DISK_USB=$(whiptail --title "Time Capsule USB disk Name" --inputbox "Enter Time Capsule USB disk name (optional):" 8 60 "" 3>&1 1>&2 2>&3)
+    if [ -z "$TC_USER" ] && [ -z "$TC_DISK" ] && [ -z "$TC_DISK_USB" ]; then
+        echo "[ERROR] Nothing to mount. At least one input among User, DISK or USB Disk is required. Process aborted."
+        exit 1
+    fi
     whiptail --title "Mount at Startup" --yesno "Do you want to enable mount at startup?" 8 60
     STARTUP_MOUNT_Q=$?
     if [ $STARTUP_MOUNT_Q -eq 0 ]; then
