v2.0.3-c1

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.0.3-c0
+TCPROXY_COMMIT=v2.0.3-c1
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.0.2
 
@@ -239,19 +239,23 @@ deflating_vm() {
 }
 
 umount_srv_tcproxy() {
-    MAX_RETRIES_UM=5
+    MAX_RETRIES_UM=3
     RETRY_COUNT_UM=0
-    while mountpoint -q "/srv/tcproxy"; do
+    # while mountpoint -q "/srv/tcproxy"; do
+    while mountpoint "/srv/tcproxy"; do
         RETRY_COUNT_UM=$((RETRY_COUNT + 1))
         if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
             logm "[ERROR] Max retries for umount_srv_tcproxy reached. Exiting..."
             exit 1
         fi
-        if sudo umount /srv/tcproxy >/dev/null 2>&1; then
+        RESPONSE_UM=$(sudo umount /srv/tcproxy 2>&1)
+        if [ $? -eq 0 ]; then
             logsm "umount of /srv/tcproxy successful..."
         else
+            logm "Failed to unmount /srv/tcproxy. $RESPONSE_UM"
             sleep 5 
-            if  mountpoint -q "/srv/tcproxy"; then
+            RESPONSE_F_UM=$(sudo umount -f /srv/tcproxy 2>&1); 
+            if [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
                 if sudo umount -f /srv/tcproxy >/dev/null 2>&1; then
                     logm "[INFO] forced unmount of /srv/tcproxy successful..."
                 else
@@ -437,7 +441,7 @@ tcproxy_up() {
     # Verify host mount
     RETRY_INTERVAL_MO=5
     RETRY_COUNT_MO=0
-    MAX_RETRIES_MO=10
+    MAX_RETRIES_MO=5
     while ! mountpoint -q /srv/tcproxy >/dev/null 2>&1; do
         RETRY_COUNT_MO=$((RETRY_COUNT + 1))
         if [ $RETRY_COUNT_MO -ge $MAX_RETRIES_MO ]; then
