v2.1.0-e6

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.0-e5
+TCPROXY_COMMIT=v2.1.0-e6
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.0.4
 #/heads/branch or /tags/version for releases
@@ -287,54 +287,39 @@ umount_srv_tcproxy() {
     RETRY_COUNT_UM=0
 
     # List of directories to unmount
-    MOUNT_POINTS=(
-        "/srv/tcproxy/$TC_DISK_USB"
-        "/srv/tcproxy/$TC_USER"
-        "/srv/tcproxy/$TC_DISK"
-    )
-
+    MOUNT_POINTS=()  # Initialize an empty array
+    if [[ -n $TC_DISK_USB ]]; then MOUNT_POINTS+=("/srv/tcproxy/$TC_DISK_USB"); fi
+    if [[ -n $TC_USER ]]; then MOUNT_POINTS+=("/srv/tcproxy/$TC_USER"); fi
+    if [[ -n $TC_DISK ]]; then MOUNT_POINTS+=("/srv/tcproxy/$TC_DISK"); fi
     for MOUNT_POINT in "${MOUNT_POINTS[@]}"; do
-        # Check if the mount point exists and is mounted
-        if mountpoint -q "$MOUNT_POINT"; then
-            RETRY_COUNT_UM=0
-
-            while [ $RETRY_COUNT_UM -lt $MAX_RETRIES_UM ]; do
-                RESPONSE_UM=$(sudo umount "$MOUNT_POINT" 2>&1)
-                if [ $? -eq 0 ]; then
-                    logsm "umount of $MOUNT_POINT successful..."
+        RETRY_COUNT_UM=0
+        while [ $RETRY_COUNT_UM -lt $MAX_RETRIES_UM ]; do
+            RESPONSE_UM=$(sudo umount "$MOUNT_POINT" 2>&1)
+            echo $RESPONSE_UM
+            if [ $? -eq 0 ] || [ $? -eq 32 ]; then
+                logm "umount of $MOUNT_POINT successful..."
+                break
+            else
+                logm "Failed to unmount $MOUNT_POINT. $RESPONSE_UM. Forcing umount..."
+                sleep 5
+                RESPONSE_F_UM=$(sudo umount -f "$MOUNT_POINT" 2>&1)
+                if [[ $? -eq 0 ]]; then
+                    logm "[INFO] Forced unmount of $MOUNT_POINT successful..."
                     break
+                elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
+                    logm "[ERROR $RESPONSE_F_UM] Please reboot and retry. Process aborted."
+                    exit 1
                 else
-                    logm "Failed to unmount $MOUNT_POINT. $RESPONSE_UM"
-                    sleep 5
-                    RESPONSE_F_UM=$(sudo umount -f "$MOUNT_POINT" 2>&1)
-                    if [[ $? -eq 0 ]]; then
-                        logm "[INFO] Forced unmount of $MOUNT_POINT successful..."
-                        break
-                    elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
-                        logm "[ERROR $RESPONSE_F_UM] Please reboot and retry. Process aborted."
-                        exit 1
-                    else
-                        logm "[ERROR $RESPONSE_F_UM] Cannot unmount $MOUNT_POINT. Is the mount in use? Process aborted."
-                        exit 1
-                    fi
+                    logm "[ERROR $RESPONSE_F_UM] Cannot unmount $MOUNT_POINT. Is the mount in use? Process aborted."
+                    exit 1
                 fi
-
-                RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
-                logm "Retrying unmount for $MOUNT_POINT... attempt $RETRY_COUNT_UM"
-            done
-
-            if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
-                logm "[ERROR] Max retries for unmounting $MOUNT_POINT reached. Exiting..."
-                exit 1
             fi
-
-        else
-            logm "$MOUNT_POINT is not mounted. Skipping..."
-        fi
+            RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
+            logm "Retrying unmount for $MOUNT_POINT... attempt $RETRY_COUNT_UM"
+        done
     done
-    logsm "umount of all specified mount points completed."
+    logm "umount of all specified mount points completed."
 }
-
 
 stopping_VM() {
     if pgrep -f "mac=02:D2:46:5B:4E:84" >/dev/null 2>&1; then
@@ -488,32 +473,15 @@ https://github.com/leobrigassi/time_capsule_proxy
 }
 
 test_VM_mount() {
-    if [[ -z $TC_USER ]]; then
-        if $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'mount -a && mount | grep -q //'$TC_IP'/'$TC_DISK''; then
-            logm "VM connected to Time Capsule..."
-        else 
-            logm "[ERROR] VM unable to connect to Time Capsule folder $TC_IP/$TC_DISK. Please check credentials and IPv4 and run install again."
-            exit 1
-        fi
-    else
-        if $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'mount -a && mount | grep -q //'$TC_IP'/'$TC_USER''; then
-            if $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'mount -a && mount | grep -q //'$TC_IP'/'$TC_DISK''; then
-                :
-            else
-                logm "[ERROR] VM unable to connect to Time Capsule folder $TC_IP/$TC_DISK. Please check credentials and IPv4 and run install again."
-                exit 1
-            fi
-        logm "VM connected to Time Capsule..."
-        else
-            logm "[ERROR] VM unable to connect to Time Capsule folder $TC_IP/$TC_USER. Please check credentials and IPv4 and run install again."
-            exit 1
-        fi
-    fi
+    if [[ -n $TC_DISK_USB ]]; then if $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'mount -a && mount | grep -q //'$TC_IP'/'$TC_DISK_USB''; then logm "$TC_DISK_USB mounted in VM..."; else logm "[ERROR] VM unable to mount to Time Capsule folder $TC_IP/$TC_DISK_USB. Please check credentials or IPv4 and run install again."; fi; fi
+    if [[ -n $TC_USER ]]; then if $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'mount -a && mount | grep -q //'$TC_IP'/'$TC_USER''; then logm "$TC_USER mounted in VM..."; else logm "[ERROR] VM unable to mount to Time Capsule folder $TC_IP/$TC_USER. Please check credentials or IPv4 and run install again."; fi; fi
+    if [[ -n $TC_DISK ]]; then if $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'mount -a && mount | grep -q //'$TC_IP'/'$TC_DISK''; then logm "$TC_DISK mounted in VM..."; else logm "[ERROR] VM unable to mount to Time Capsule folder $TC_IP/$TC_DISK. Please check credentials or IPv4 and run install again."; fi; fi
 }
 
 check_smb_share() {
-    smbclient //127.0.0.1/$TC_DISK -U root%$TC_PASSWORD --port=50445 -c 'exit'
-    return $?
+    if [[ -n $TC_DISK_USB ]]; then smbclient //127.0.0.1/$TC_DISK_USB -U root%$TC_PASSWORD --port=50445 -c 'exit'; return $?; fi
+    if [[ -n $TC_USER ]]; then smbclient //127.0.0.1/$TC_USER -U root%$TC_PASSWORD --port=50445 -c 'exit'; return $?; fi
+    if [[ -n $TC_DISK ]]; then smbclient //127.0.0.1/$TC_DISK -U root%$TC_PASSWORD --port=50445 -c 'exit'; return $?; fi
 }
 
 tcproxy_up() {
@@ -714,6 +682,7 @@ save_ENVs_to_file() {
     echo "TC_IP=$TC_IP" >> $TCP_ENV
     echo "TC_DISK=$TC_DISK" >> $TCP_ENV
     echo "TC_FSTAB_USER=$TC_FSTAB_USER" >> $TCP_ENV
+    echo "TC_USER=$TC_USER" >> $TCP_ENV
     echo "TC_PASSWORD=$TC_PASSWORD" >> $TCP_ENV
     echo "TCPROXY_SERVICE_FILE=$TCPROXY_SERVICE_FILE" >> $TCP_ENV
     echo "TCPROXY_SERVICE_TEMP_FILE=$TCPROXY_SERVICE_TEMP_FILE" >> $TCP_ENV
@@ -893,7 +862,7 @@ elif [[ $1 == "-u" ]] || [[ $1 == "--up" ]]; then
     tcproxy_up
     footer
 elif [[ $1 == "-d" ]] || [[ $1 == "--down" ]]; then
-    DESCR_COM="Unmounting share and stopping VM..."; header
+    DESCR_COM="Umounting share and stopping VM..."; header
     umount_srv_tcproxy
     sleep 5
     stopping_VM
