v2.1.1-d3

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,7 +1,7 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.1-d2
-TCPROXY_BRANCH=/heads/dev
+TCPROXY_COMMIT=v2.1.1-d3
+TCPROXY_BRANCH=/heads/beta
 TCPROXY_RELEASE=v2.1.0
 #/heads/branch or /tags/version for releases
 
@@ -780,25 +780,6 @@ keep_log_small() {
 }
 
 # tcproxy logic
-if [[ $TCPROXY_BRANCH == "/heads/beta" ]] || [[ $TCPROXY_BRANCH == "/heads/dev" ]]; then
-    BETA_WARNING="You have selected the beta branch of tcproxy.
-What we are testing:
-- additional sudo checks for users with lower privileges. Such users will be prompted for sudo password
-- additional checks for user inputs. If USERNAME is not provided then at least DISK or USB_DISK must be provided.
-
-Do you want to continue?"
-    echo "------------------------------------------------------------------"
-    echo "---------- YOU HAVE SELECTED THE BETA BRANCH OF TCPROXY ----------"
-    echo "---------- please provide your feedback on: ----------------------"
-    echo "---------- https://github.com/leobrigassi/time-capsule-proxy -----"
-    echo "------------------------------------------------------------------"
-    countdown 7
-    whiptail --title "tcproxy $TCPROXY_COMMIT installation GUI" --yesno "$BETA_WARNING" 15 60
-    BETA_CONFIRMATION=$?
-    if [ $BETA_CONFIRMATION -ne 0 ]; then
-        echo "GUI Process Aborted. tcproxy has not been installed."; exit 1
-    fi
-fi
 echo ""
 echo "tcproxy requires sudo privileges to install. If prompted insert your sudo credentials:"
 if sudo -n true 2>/dev/null; then echo "Sudo session is active and validated."
@@ -856,6 +837,25 @@ elif [[ $1 == "" ]] && [[ ! $TC_PASSWORD == "" ]]; then
     footer
 elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
     DESCR_COM="Installing..."; header
+    if [[ $TCPROXY_BRANCH == "/heads/beta" ]] || [[ $TCPROXY_BRANCH == "/heads/dev" ]]; then
+    BETA_WARNING="You have selected the beta branch of tcproxy.
+What we are testing:
+- additional sudo checks for users with lower privileges. Such users will be prompted for sudo password
+- additional checks for user inputs. If USERNAME is not provided then at least DISK or USB_DISK must be provided.
+
+Do you want to continue?"
+        echo "------------------------------------------------------------------"
+        echo "---------- YOU HAVE SELECTED THE BETA BRANCH OF TCPROXY ----------"
+        echo "---------- please provide your feedback on: ----------------------"
+        echo "---------- https://github.com/leobrigassi/time-capsule-proxy -----"
+        echo "------------------------------------------------------------------"
+        countdown 7
+        whiptail --title "tcproxy $TCPROXY_COMMIT installation GUI" --yesno "$BETA_WARNING" 15 60
+        BETA_CONFIRMATION=$?
+        if [ $BETA_CONFIRMATION -ne 0 ]; then
+            echo "GUI Process Aborted. tcproxy has not been installed."; exit 1
+        fi
+    fi
     create_tcproxy_folder
     download_latest_script
     check_system_requirements
