v2.0.0_beta1.114_logm

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_VERSION=v2.0.0_beta1.113_logm
+TCPROXY_VERSION=v2.0.0_beta1.114_logm-local
 TCPROXY_BRANCH=v2.0.0
 
 logc() {
@@ -96,7 +96,7 @@ tcproxy_web_install_env_check() {
     if [[ ! -e .tcproxy ]]; then 
         return 1
     else
-        source .tcproxy >/dev/null 2>&1
+        source .tcproxy
         return 0
     fi
 }
@@ -135,25 +135,25 @@ github_download() {
 check_system_requirements() {
     ARCH=$(uname -m)
     if [[ $ARCH == x86_64* ]]; then
-        if ! which qemu-system-x86_64 > /dev/null; then
-        logsm "qemu not detected.
+        if ! which qemu-system-x86_64 >/dev/null 2>&1; then
+        logm "qemu not detected.
         sudo apt install qemu-system-x86_64 qemu-kvm
         please install and try again."
         exit 1
         fi
     elif [[ $ARCH == aarch64* ]]; then
-        if ! which qemu-system-aarch64 > /dev/null && ! which qemu-system-x86_64 > /dev/null; then
-        logsm "Qemu not detected.
+        if ! which qemu-system-aarch64 >/dev/null 2>&1 && ! which qemu-system-x86_64 >/dev/null 2>&1; then
+        logm "Qemu not detected.
         sudo apt install qemu-system-aarch64 qemu-kvm
         Please install and try again."
         exit 1
         fi
     else
-        logsm "System not supported. Please run from x86_64 or aarch64 systems."
+        logm "System not supported. Please run from x86_64 or aarch64 systems."
         exit 1
     fi
     if ! which smbclient >/dev/null 2>&1; then
-        logsm "smbclient is required for this script to work correctly. 
+        logm "smbclient is required for this script to work correctly. 
         sudo apt install smbclient
         Please install and try again."
         exit 1
@@ -161,12 +161,12 @@ check_system_requirements() {
 }
 
 testing_ssh_premission_requirements() {
-    ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "ls" > /dev/null 2>&1
+    ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "ls"
     SUDOREQUIREDEXIT=$?
     if [ $SUDOREQUIREDEXIT -eq 0 ]; then
         SUDOREQUIRED=""
     else
-        sudo ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "ls" > /dev/null 2>&1
+        sudo ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "ls"
         SUDOREQUIREDEXIT=$?
         if [ $SUDOREQUIREDEXIT -eq 0 ]; then
             SUDOREQUIRED="sudo "
@@ -243,11 +243,11 @@ deflating_vm() {
 
 stopping_installed_VMs_and_mounts() {
     if mountpoint -q "/srv/tc-proxy"; then
-        if sudo umount /srv/tc-proxy 2>/dev/null; then
-            logsm "Mountpoint /srv/tc-proxy detected. Unmounting..."
+        if sudo umount /srv/tc-proxy >/dev/null 2>&1; then
+            logm "Mountpoint /srv/tc-proxy detected. Unmounting..."
         else
-            logsm "[INFO] Cannot gracefully unmount /srv/tc-proxy. Forcing unmount..."
-            sudo umount -f /srv/tc-proxy 2>/dev/null
+            logm "[INFO] Cannot gracefully unmount /srv/tc-proxy. Forcing unmount..."
+            sudo umount -f /srv/tc-proxy
             sleep 2
             if mountpoint -q "/srv/tc-proxy"; then
                 logsm "[ERROR] Cannot unmount /srv/tc-proxy. Please umount and run setup again."
@@ -255,13 +255,13 @@ stopping_installed_VMs_and_mounts() {
             fi
         fi
     fi
-    if pgrep -f "mac=02:D2:46:5B:4E:84" > /dev/null 2>&1; then
+    if pgrep -f "mac=02:D2:46:5B:4E:84" >/dev/null 2>&1; then
         logsm "VM detected. Sending poweroff command..."
         $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "poweroff"
         TIMEOUT=60
         INTERVAL=5
         ELAPSED=0
-        while pgrep -f "mac=02:D2:46:5B:4E:84" > /dev/null 2>&1; do
+        while pgrep -f "mac=02:D2:46:5B:4E:84" >/dev/null 2>&1; do
             sleep $INTERVAL
             ELAPSED=$((ELAPSED + INTERVAL))
             if [ $ELAPSED -ge $TIMEOUT ]; then
@@ -319,16 +319,16 @@ check_VM_status() {
 }
 
 creating_mountpoint_folder() {
-    sudo mkdir -p /srv/tc-proxy >/dev/null 2>&1
+    sudo mkdir -p /srv/tc-proxy
 }
 
 provision_VM() {
     logsm "Provisioning VM..."
     # Configure VMroot passwd, /etc/fstab, samba
-    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'echo -e "'$TC_PASSWORD'\n'$TC_PASSWORD'" | passwd' >/dev/null 2>&1
-    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "cp /etc/fstab /etc/fstab.bak && sed '/#_Run_setup-vm-proxy-time-capsule.sh_on_host_to_edit_this_line/d' /etc/fstab.bak > /etc/fstab.new && cp /etc/fstab.new /etc/fstab" >/dev/null 2>&1
-    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'echo "//'$TC_IP'/'$TC_FOLDER' /mnt/tc cifs _netdev,x-systemd.after=network-online.target'$TC_FSTAB_USER',password='$TC_PASSWORD',sec=ntlm,uid=0,vers=1.0,rw,file_mode=0777,dir_mode=0777 0 0 #_Run_setup-vm-proxy-time-capsule.sh_on_host_to_edit_this_line" | tee -a /etc/fstab.new && mv /etc/fstab.new /etc/fstab' >/dev/null 2>&1
-    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'echo -e "'$TC_PASSWORD'\n'$TC_PASSWORD'" | smbpasswd -a root' >/dev/null 2>&1
+    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'echo -e "'$TC_PASSWORD'\n'$TC_PASSWORD'" | passwd'
+    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 "cp /etc/fstab /etc/fstab.bak && sed '/#_Run_setup-vm-proxy-time-capsule.sh_on_host_to_edit_this_line/d' /etc/fstab.bak > /etc/fstab.new && cp /etc/fstab.new /etc/fstab"
+    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'echo "//'$TC_IP'/'$TC_FOLDER' /mnt/tc cifs _netdev,x-systemd.after=network-online.target'$TC_FSTAB_USER',password='$TC_PASSWORD',sec=ntlm,uid=0,vers=1.0,rw,file_mode=0777,dir_mode=0777 0 0 #_Run_setup-vm-proxy-time-capsule.sh_on_host_to_edit_this_line" | tee -a /etc/fstab.new && mv /etc/fstab.new /etc/fstab'
+    $SUDOREQUIRED ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'echo -e "'$TC_PASSWORD'\n'$TC_PASSWORD'" | smbpasswd -a root'
 }
 
 test_VM_mount() {
@@ -342,7 +342,7 @@ test_VM_mount() {
 }
 
 check_smb_share() {
-    smbclient //127.0.0.1/tc-proxy -U root%$TC_PASSWORD --port=50445 -c 'exit' > /dev/null 2>&1
+    smbclient //127.0.0.1/tc-proxy -U root%$TC_PASSWORD --port=50445 -c 'exit'
     return $?
 }
 
@@ -382,10 +382,10 @@ tcproxy_up() {
     # Verify host mount
     if ! mountpoint -q /srv/tc-proxy; then
         logsm "Remounting /srv/tc-proxy..."
-        sudo umount -l /srv/tc-proxy  > /dev/null 2>&1
+        sudo umount -l /srv/tc-proxy
         sudo mount -t cifs //127.0.0.1/tc-proxy /srv/tc-proxy/ -o password="$TC_PASSWORD""$TC_FSTAB_USER",rw,uid="$PUID",iocharset=utf8,vers=3.0,nofail,file_mode=0775,dir_mode=0775,port=50445 >> "$LOG_FILE"
     fi
-    logsm "/srv/tc-proxy mounted and accessible"
+    logm "/srv/tc-proxy mounted and accessible"
     return 0
 }
 
@@ -423,21 +423,21 @@ WantedBy=multi-user.target" > "$TCP_SERVICE_TEMP_FILE"
 remove_system_service() {
         logsm "Scanning for previously installed daemons..."
         if [[ -f /etc/systemd/system/time-capsule-proxy.service ]]; then
-            sudo systemctl stop time-capsule-proxy.service >/dev/null 2>&1
-            sudo systemctl disable time-capsule-proxy.service >/dev/null 2>&1
-            sudo rm /etc/systemd/system/time-capsule-proxy.service >/dev/null 2>&1
+            sudo systemctl stop time-capsule-proxy.service
+            sudo systemctl disable time-capsule-proxy.service
+            sudo rm /etc/systemd/system/time-capsule-proxy.service
         fi
         if [[ -f /etc/systemd/system/tcproxy.service ]]; then
-            sudo systemctl stop tcproxy.service >/dev/null 2>&1
-            sudo systemctl disable tcproxy.service >/dev/null 2>&1
-            sudo rm /etc/systemd/system/tcproxy.service >/dev/null 2>&1
+            sudo systemctl stop tcproxy.service
+            sudo systemctl disable tcproxy.service
+            sudo rm /etc/systemd/system/tcproxy.service
         fi
 }
 
 install_system_service() {
-        sudo cp $TCP_SERVICE_TEMP_FILE $TIME_CAPSULE_PROXY_SERVICE >/dev/null 2>&1
+        sudo cp $TCP_SERVICE_TEMP_FILE $TIME_CAPSULE_PROXY_SERVICE
         sudo systemctl daemon-reload
-        sudo systemctl enable tcproxy.service >/dev/null 2>&1
+        sudo systemctl enable tcproxy.service
         if sudo systemctl start tcproxy.service; then
             logsm "Service enabled at boot."
         else logsm "[ERROR] Failed to start tcproxy.service - Error code $?"
@@ -452,7 +452,7 @@ ssh_vm() {
 
 remove_tcproxy_env() {
     if [[ -f $TCP_ENV ]]; then 
-    rm $TCP_ENV >/dev/null 2>&1
+    rm $TCP_ENV
     fi
     logsm ".tcproxy.env removed"
 }
@@ -584,8 +584,8 @@ else
     if [[ $1 == "" ]]; then
         if [[ $WEB_INST -eq 1 ]]; then
         echo "tcproxy $TCPROXY_VERSION: web install..."
-        create_tcproxy_folder  >/dev/null 2>&1
-        github_download  >/dev/null 2>&1
+        create_tcproxy_folder
+        github_download
         elif tcproxy_env_check; then
             echo "tcproxy: no arguments. Defaulting to 'tcproxy --up'"
             tcproxy_up
