v2.0.0_beta1.3

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_VERSION=v2.0.0_beta1.2
+TCPROXY_VERSION=v2.0.0_beta1.3
 TCPROXY_BRANCH=v2.0.0
 
 tcproxy_log() {
@@ -478,10 +478,10 @@ elif [[ $1 == "-t" ]]; then
     tcproxy_log "[  ] Installing..."
 else 
     if [[ $1 == "" ]]; then
-        if ! read -t 1 WEB_INSTALL; then
-        echo "WEB-install detected"
+        if ! read -t 1 "tcproxy: installation failed. Please report." WEB_INSTALL; then
+        echo "read failed"
+        WEB_INSTALL="TRUE"
         create_tcproxy_folder  >/dev/null 2>&1
-        WEB_INSTALL=TRUE
         github_download  >/dev/null 2>&1
         elif tcproxy_env_check; then
             echo "web install NOT detected. bringin up qemu"
