v2.0.3-c2

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.0.3-c1
+TCPROXY_COMMIT=v2.0.3-c2
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.0.2
 
@@ -243,7 +243,7 @@ umount_srv_tcproxy() {
     RETRY_COUNT_UM=0
     # while mountpoint -q "/srv/tcproxy"; do
     while mountpoint "/srv/tcproxy"; do
-        RETRY_COUNT_UM=$((RETRY_COUNT + 1))
+        RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
         if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
             logm "[ERROR] Max retries for umount_srv_tcproxy reached. Exiting..."
             exit 1
@@ -255,16 +255,14 @@ umount_srv_tcproxy() {
             logm "Failed to unmount /srv/tcproxy. $RESPONSE_UM"
             sleep 5 
             RESPONSE_F_UM=$(sudo umount -f /srv/tcproxy 2>&1); 
-            if [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
-                if sudo umount -f /srv/tcproxy >/dev/null 2>&1; then
-                    logm "[INFO] forced unmount of /srv/tcproxy successful..."
-                else
-                    EXIT_CODE=$?
-                    logm "[ERROR $EXIT_CODE] Cannot unmount /srv/tcproxy. Is the mount in use? Installation aborted."
+            if [[ $? -eq 0 ]]; then
+                logm "[INFO] forced unmount of /srv/tcproxy successful..."
+            elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
+                    logm "[ERROR $$RESPONSE_F_UM] Please reboot and retry. Installation aborted."
                     exit 1
-                fi
-            else
-                logm "umount (slow) of /srv/tcproxy successful..."
+            else 
+                logm "[ERROR $$RESPONSE_F_UM] Cannot unmount /srv/tcproxy. Is the mount in use? Installation aborted."
+                exit 1
             fi
         fi
         sleep 5
