v2.1.3_b5

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.3_b4
+TCPROXY_COMMIT=v2.1.3_b5
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.1.3
 #/heads/branch or /tags/version for releases
@@ -260,27 +260,27 @@ umount_srv_tcproxy() {
         while [ $RETRY_COUNT_UM -lt $MAX_RETRIES_UM ]; do
             RESPONSE_UM=$(sudo umount "$MOUNT_POINT_UM" 2>&1)
             if [ $? -eq 0 ] || [ $? -eq 32 ] || echo "$RESPONSE_UM" | grep -q "not mounted"; then
-                logm "umount of $MOUNT_POINT_UM successful..."
+                logm "Host umount of [$MOUNT_POINT_UM] successful..."
                 break
             else
-                if ! mountpoint -q /srv/tcproxy/$MOUNT_POINT_M; then logsm "/srv/tcproxy/$MOUNT_POINT_M not a mountpoint"; break; fi
-                logm "Failed to unmount $MOUNT_POINT_UM . $RESPONSE_UM. Forcing umount..."
+                if ! mountpoint -q /srv/tcproxy/$MOUNT_POINT_M; then logsm "Host folder [/srv/tcproxy/$MOUNT_POINT_M] is not a mountpoint"; break; fi
+                logm "Host failed to unmount [$MOUNT_POINT_UM]. $RESPONSE_UM. Forcing umount..."
                 sleep 5
                 RESPONSE_F_UM=$(sudo umount -f "$MOUNT_POINT_UM" 2>&1)
                 if [[ $? -eq 0 ]]; then
-                    logm "[INFO] Forced unmount of $MOUNT_POINT_UM successful..."
+                    logm "[INFO] Forced unmount of [$MOUNT_POINT_UM] successful..."
                     break
                 elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
                     logm "[ERROR $RESPONSE_F_UM] Please reboot and retry. Process aborted."
                 else
-                    logm "[ERROR $RESPONSE_F_UM] Cannot unmount $MOUNT_POINT_UM . Is the mount in use?"
+                    logm "[ERROR $RESPONSE_F_UM] Cannot unmount [$MOUNT_POINT_UM] . Is the mount in use?"
                 fi
             fi
             RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
-            logm "Retrying unmount for $MOUNT_POINT_UM ... attempt $RETRY_COUNT_UM"
+            logm "Host retrying unmount for [$MOUNT_POINT_UM] ... attempt $RETRY_COUNT_UM"
         done
     done
-    logm "umount routine of all specified mount points completed."
+    logm "Host umount routine of all specified mount points completed."
 }
 
 stopping_VM() {
