v2.1.1-d1

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.1-d0
+TCPROXY_COMMIT=v2.1.1-d1
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.1.0
 #/heads/branch or /tags/version for releases
@@ -791,7 +791,7 @@ if [[ $TCPROXY_BRANCH == "/heads/beta" ]] || [[ $TCPROXY_BRANCH == "/heads/dev" 
     whiptail --title "tcproxy $TCPROXY_COMMIT installation GUI" --yesno "$BETA_WARNING" 15 60
     BETA_CONFIRMATION=$?
     if [ $BETA_CONFIRMATION -ne 0 ]; then
-        echo "GUI Process Aborted. tcproxy has not been installed."; countdown 5; exit 1
+        echo "GUI Process Aborted. tcproxy has not been installed."; exit 1
     fi
 fi
 echo ""
