v2.1.1-c4

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.1.1-a1
+TCPROXY_COMMIT=v2.1.1-c4
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.1.0
 #/heads/branch or /tags/version for releases
@@ -187,11 +187,10 @@ prompt_user_inputs() {
     echo "GUI closed unexpectedly. Running text based setup.
 Close any app or terminal window using /srv/tcproxy before continuing."
     read -p "[INPUT] Continue? (y/N): " CONFIRM_INSTALL
-
     if [[ "$CONFIRM_INSTALL" =~ ^[Yy]$ ]]; then
         :
     else
-        logm "[INFO] Process Aborted. No change has been performed."
+        logm "[INFO] Setup aborted. tcproxy has not been installed."
         exit 1
     fi
     read -p "[INPUT] Time Capsule IPv4 (e.g. 192.168.1.10): " TC_IP
@@ -646,6 +645,16 @@ ssh_vm() {
     logsm "ssh-out"
 }
 
+countdown() {
+    local SECONDS=$1
+    while [ $SECONDS -gt 0 ]; do
+        echo -ne "Time remaining: ${SECONDS} seconds\033[0K\r"
+        sleep 1
+        ((SECONDS--))
+    done
+    echo ""
+}
+
 remove_tcproxy_env() {
     if [[ -f $TCP_ENV ]]; then 
     sudo rm $TCP_ENV
@@ -720,7 +729,6 @@ post_install_cleanup() {
     logsc sudo rm "leobrigassi.code-workspace"
     logsc sudo rm $INSTALLER_PATH/.tcproxy
     logsc sudo rm $TCPROXY_PATH/.tcproxy
-    logsc sudo rm $TCPROXY_PATH/.web-install-tcproxy
     logsc sudo rm $TCPROXY_PATH/.tcproxy-boot-load.service
     logsc sudo rm $TCPROXY_PATH/.tcproxy-boot-load.timer
 }
@@ -772,23 +780,33 @@ keep_log_small() {
 }
 
 # tcproxy logic
-sudo_output=$(sudo -v 2>&1)
-
-# Check if the output contains the word 'password'
-if echo "$sudo_output" | grep -q "password"; then
-    echo "Sudo is asking for a password."
-    # Handle the case where sudo asks for a password
-else
-    echo "Sudo did not ask for a password."
-    # Handle the case where no password is required
+if [[ $TCPROXY_BRANCH == "/heads/beta" ]]; then
+    BETA_WARNING="You have selected the beta branch of tcproxy.\nWhat we are testing:\n - additional sudo checks for users with lower privileges. Such users will be prompted for sudo password\n - additional checks for user inputs. If USERNAME is not provided then at least DISK or USB_DISK must be provided.\n\nDo you want to continue?"
+    whiptail --title "tcproxy $TCPROXY_COMMIT installation GUI" --yesno "$BETA_WARNING" 15 60
+    BETA_CONFIRMATION=$?
+    if [ $BETA_CONFIRMATION -ne 0 ]; then
+        echo "GUI Process Aborted. tcproxy has not been installed."; countdown 5; exit 1
+    fi
 fi
-read -p "[INPUT] Continue? (y/N): " SUDOPASSWORDTEST
-
-
+echo ""
+echo "tcproxy requires sudo privileges to install. If prompted insert your sudo credentials:"
+if sudo -n true 2>/dev/null; then echo "Sudo session is active and validated."
+else
+    SUDO_OUTPUT=$(sudo -v 2>&1)
+    if sudo -n true 2>/dev/null; then
+        echo "Sudo session is active and validated."
+    else
+        echo "Sudo session is not active. A password is required."
+        echo "Please run [ ./tcproxy --install ] from the install directory [ tcproxy/ ] and insert your sudo password when prompted."
+        create_tcproxy_folder
+        download_latest_script
+        exit 1
+    fi
+fi
 if [[ "$(pwd)" =~ \  ]]; then echo "[ERROR] The installation path contains spaces, which is not supported."; echo "Please move the script to a directory without spaces and try again."; exit 1; fi
 SCRIPT_COMMAND="$0 $@"
 if [ -n "$INVOCATION_ID" ]; then logsc tcproxy_up; exit 0; fi
-if [ ! -t 0 ]; then set -- "--install"; fi
+if [ ! -t 0 ]; then set -- "--install"; WEB_INSTALL="TRUE"; fi
 if [[ -e $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.tcproxy.env ]] && [[ -s $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.tcproxy.env ]]; then 
     source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.tcproxy.env"
 else echo "[INFO] Installation not detected. Run [./tcproxy --install] to setup your system."; create_tcproxy_folder; fi
@@ -798,7 +816,6 @@ if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
     footer
 elif [[ $1 == "-v" ]] || [[ $1 == "--version" ]]; then
     logm "tcproxy: $TCPROXY_COMMIT"
-    # logsc $SUDOREQUIRED VM_VERSION=$(ssh root@localhost -i ./id_rsa_vm -o StrictHostKeyChecking=no -p50022 'grep "^VERSION=" /usr/local/bin/.metrics.ev | cut -d'=' -f2')
     footer
 elif [[ $1 == "--uninstall" ]]; then
     DESCR_COM="Uninstalling tcproxy..."; header
@@ -829,12 +846,12 @@ elif [[ $1 == "" ]] && [[ ! $TC_PASSWORD == "" ]]; then
 elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
     DESCR_COM="Installing..."; header
     create_tcproxy_folder
+    download_latest_script
     check_system_requirements
     whiptail --title "tcproxy $TCPROXY_COMMIT installation GUI" --yesno "Close any app or terminal window using /srv/tcproxy before continuing.\n\nDo you want to continue?" 15 60
     INSTALL_CONFIRMATION=$?
     if [ $INSTALL_CONFIRMATION -ne 0 ]; then
-        echo "[INFO] Process Aborted. No change has been performed."
-        prompt_user_inputs
+        if [[ $WEB_INSTALL != "TRUE" ]]; then prompt_user_inputs; else echo "[INFO] GUI Process Aborted. tcproxy has not been installed."; exit 1; fi
     fi
     TC_IP=$(whiptail --title "Time Capsule IPv4" --inputbox "Enter Time Capsule IPv4 (e.g., 192.168.1.10):" 8 60 "" 3>&1 1>&2 2>&3)
     if [ -z "$TC_IP" ]; then
@@ -847,19 +864,16 @@ elif [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
         echo "[ERROR] PASSWORD is required. Process aborted."
         exit 1
     fi
-    TC_DISK=$(whiptail --title "Time Capsule DISK name" --inputbox "Enter Time Capsule DISK name (e.g., Data):" 8 60 "" 3>&1 1>&2 2>&3)
-    # if [ -z "$TC_DISK" ]; then
-    #     echo "[ERROR] DISK name is required. Process aborted."
-    #     exit 1
-    # fi
+    TC_DISK=$(whiptail --title "Time Capsule DISK name" --inputbox "Enter Time Capsule DISK name e.g., Data (optional):" 8 60 "" 3>&1 1>&2 2>&3)
     TC_DISK_USB=$(whiptail --title "Time Capsule USB disk Name" --inputbox "Enter Time Capsule USB disk name (optional):" 8 60 "" 3>&1 1>&2 2>&3)
+    if [ -z "$TC_USER" ] && [ -z "$TC_DISK" ] && [ -z "$TC_DISK_USB" ]; then
+        echo "[ERROR] Nothing to mount. At least one input among User, DISK or USB Disk is required. Process aborted."
+        exit 1
+    fi
     whiptail --title "Mount at Startup" --yesno "Do you want to enable mount at startup?" 8 60
     STARTUP_MOUNT_Q=$?
     if [ $STARTUP_MOUNT_Q -eq 0 ]; then
         STARTUP_MOUNT="Y"
-    fi
-    if [ -z "$INSTALL_CONFIRMATION" ]; then 
-        prompt_user_inputs
     fi
     github_download
     deflating_vm
