v2.0.0_beta1.275

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_VERSION=v2.0.0_beta1.274
+TCPROXY_VERSION=v2.0.0_beta1.275
 TCPROXY_BRANCH=v2.0.0
 
 define_tcproxy_env_vars() {
@@ -281,20 +281,22 @@ deflating_vm() {
 }
 
 unmount_srv_tcproxy() {
-    if sudo umount /srv/tcproxy >/dev/null 2>&1; then
-        logm "Unmount of /srv/tcproxy successful..."
-    else
-        sleep 5 
-        if  mountpoint -q "/srv/tcproxy"; then
-            if sudo umount -f /srv/tcproxy >/dev/null 2>&1; then
-                logm "[INFO] forced unmount of /srv/tcproxy successful..."
-            else
-                EXIT_CODE=$?
-                logm "[ERROR $EXIT_CODE] Cannot unmount /srv/tcproxy. Please check your system and run tcproxy -i again."
-                exit 1
-            fi
+    if  mountpoint -q "/srv/tcproxy"; then
+        if sudo umount /srv/tcproxy >/dev/null 2>&1; then
+            logm "Unmount of /srv/tcproxy successful..."
         else
-            logm "Unmount (slow) of /srv/tcproxy successful..."
+            sleep 5 
+            if  mountpoint -q "/srv/tcproxy"; then
+                if sudo umount -f /srv/tcproxy >/dev/null 2>&1; then
+                    logm "[INFO] forced unmount of /srv/tcproxy successful..."
+                else
+                    EXIT_CODE=$?
+                    logm "[ERROR $EXIT_CODE] Cannot unmount /srv/tcproxy. Please check your system and run tcproxy -i again."
+                    exit 1
+                fi
+            else
+                logm "Unmount (slow) of /srv/tcproxy successful..."
+            fi
         fi
     fi
 }
