v2.0.5-d7

diff --git a/tcproxy b/tcproxy
--- a/tcproxy
+++ b/tcproxy
@@ -1,6 +1,6 @@
 #!/bin/bash
 #Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
-TCPROXY_COMMIT=v2.0.5-d6
+TCPROXY_COMMIT=v2.0.5-d7
 TCPROXY_BRANCH=/heads/dev
 TCPROXY_RELEASE=v2.0.4
 #/heads/branch or /tags/version for releases
@@ -225,62 +225,117 @@ deflating_vm() {
     sudo rm tcproxy_VM_x86.tar.gz
 }
 
+# umount_srv_tcproxy() {
+#     MAX_RETRIES_UM=3
+#     RETRY_COUNT_UM=0
+#     while ! ls /srv/tcproxy > /dev/null 2>&1; do
+#         RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
+#         if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
+#             logm "[ERROR] Max retries for umount_srv_tcproxy reached. Exiting..."
+#             exit 1
+#         fi
+#         RESPONSE_UM=$(sudo umount /srv/tcproxy 2>&1)
+#         if [ $? -eq 0 ]; then
+#             logsm "umount of /srv/tcproxy successful..."
+#         else
+#             logm "Failed to unmount /srv/tcproxy. $RESPONSE_UM"
+#             sleep 5 
+#             RESPONSE_F_UM=$(sudo umount -f /srv/tcproxy 2>&1); 
+#             if [[ $? -eq 0 ]]; then
+#                 logm "[INFO] forced unmount of /srv/tcproxy successful..."
+#             elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
+#                 logm "[ERROR $$RESPONSE_F_UM] Please reboot and retry. Process aborted."
+#                 exit 1
+#             else 
+#                 logm "[ERROR $$RESPONSE_F_UM] Cannot unmount /srv/tcproxy. Is the mount in use? Process aborted."
+#                 exit 1
+#             fi
+#         fi
+#     done
+#     RETRY_COUNT_UM=0
+#     while mountpoint -q /srv/tcproxy; do
+#         RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
+#         if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
+#             logm "[ERROR] Max retries for umount_srv_tcproxy reached. Exiting..."
+#             exit 1
+#         fi
+#         RESPONSE_UM=$(sudo umount /srv/tcproxy 2>&1)
+#         if [ $? -eq 0 ]; then
+#             logsm "umount of /srv/tcproxy successful..."
+#         else
+#             logm "Failed to unmount /srv/tcproxy. $RESPONSE_UM"
+#             sleep 5 
+#             RESPONSE_F_UM=$(sudo umount -f /srv/tcproxy 2>&1); 
+#             if [[ $? -eq 0 ]]; then
+#                 logm "[INFO] forced unmount of /srv/tcproxy successful..."
+#             elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
+#                 logm "[ERROR $RESPONSE_F_UM] Please reboot and retry. Process aborted."
+#                 exit 1
+#             else 
+#                 logm "[ERROR $RESPONSE_F_UM] Cannot unmount /srv/tcproxy. Is the mount in use? Process aborted."
+#                 exit 1
+#             fi
+#         fi
+#         logm "cannot umount /srv/tcproxy... trying again..."
+#         sleep 5
+#     done
+#     logsm "umount /srv/tcproxy completed..."
+# }
+
 umount_srv_tcproxy() {
     MAX_RETRIES_UM=3
     RETRY_COUNT_UM=0
-    while ! ls /srv/tcproxy > /dev/null 2>&1; do
-        RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
-        if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
-            logm "[ERROR] Max retries for umount_srv_tcproxy reached. Exiting..."
-            exit 1
-        fi
-        RESPONSE_UM=$(sudo umount /srv/tcproxy 2>&1)
-        if [ $? -eq 0 ]; then
-            logsm "umount of /srv/tcproxy successful..."
-        else
-            logm "Failed to unmount /srv/tcproxy. $RESPONSE_UM"
-            sleep 5 
-            RESPONSE_F_UM=$(sudo umount -f /srv/tcproxy 2>&1); 
-            if [[ $? -eq 0 ]]; then
-                logm "[INFO] forced unmount of /srv/tcproxy successful..."
-            elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
-                logm "[ERROR $$RESPONSE_F_UM] Please reboot and retry. Process aborted."
-                exit 1
-            else 
-                logm "[ERROR $$RESPONSE_F_UM] Cannot unmount /srv/tcproxy. Is the mount in use? Process aborted."
-                exit 1
-            fi
-        fi
-    done
-    RETRY_COUNT_UM=0
-    while mountpoint -q /srv/tcproxy; do
-        RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
-        if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
-            logm "[ERROR] Max retries for umount_srv_tcproxy reached. Exiting..."
-            exit 1
-        fi
-        RESPONSE_UM=$(sudo umount /srv/tcproxy 2>&1)
-        if [ $? -eq 0 ]; then
-            logsm "umount of /srv/tcproxy successful..."
-        else
-            logm "Failed to unmount /srv/tcproxy. $RESPONSE_UM"
-            sleep 5 
-            RESPONSE_F_UM=$(sudo umount -f /srv/tcproxy 2>&1); 
-            if [[ $? -eq 0 ]]; then
-                logm "[INFO] forced unmount of /srv/tcproxy successful..."
-            elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
-                logm "[ERROR $RESPONSE_F_UM] Please reboot and retry. Process aborted."
-                exit 1
-            else 
-                logm "[ERROR $RESPONSE_F_UM] Cannot unmount /srv/tcproxy. Is the mount in use? Process aborted."
+
+    # List of directories to unmount
+    MOUNT_POINTS=(
+        "/srv/tcproxy/${TC_DISK_USB}"
+        "/srv/tcproxy/${TC_USER}"
+        "/srv/tcproxy/${TC_DISK}"
+        "/srv/tcproxy"
+    )
+
+    for MOUNT_POINT in "${MOUNT_POINTS[@]}"; do
+        # Check if the mount point exists and is mounted
+        if mountpoint -q "$MOUNT_POINT"; then
+            RETRY_COUNT_UM=0
+
+            while [ $RETRY_COUNT_UM -lt $MAX_RETRIES_UM ]; do
+                RESPONSE_UM=$(sudo umount "$MOUNT_POINT" 2>&1)
+                if [ $? -eq 0 ]; then
+                    logsm "umount of $MOUNT_POINT successful..."
+                    break
+                else
+                    logm "Failed to unmount $MOUNT_POINT. $RESPONSE_UM"
+                    sleep 5
+                    RESPONSE_F_UM=$(sudo umount -f "$MOUNT_POINT" 2>&1)
+                    if [[ $? -eq 0 ]]; then
+                        logm "[INFO] Forced unmount of $MOUNT_POINT successful..."
+                        break
+                    elif [[ $RESPONSE_F_UM == *"Stale file handle"* ]]; then
+                        logm "[ERROR $RESPONSE_F_UM] Please reboot and retry. Process aborted."
+                        exit 1
+                    else
+                        logm "[ERROR $RESPONSE_F_UM] Cannot unmount $MOUNT_POINT. Is the mount in use? Process aborted."
+                        exit 1
+                    fi
+                fi
+
+                RETRY_COUNT_UM=$((RETRY_COUNT_UM + 1))
+                logm "Retrying unmount for $MOUNT_POINT... attempt $RETRY_COUNT_UM"
+            done
+
+            if [ $RETRY_COUNT_UM -ge $MAX_RETRIES_UM ]; then
+                logm "[ERROR] Max retries for unmounting $MOUNT_POINT reached. Exiting..."
                 exit 1
             fi
+
+        else
+            logm "$MOUNT_POINT is not mounted. Skipping..."
         fi
-        logm "cannot umount /srv/tcproxy... trying again..."
-        sleep 5
     done
-    logsm "umount /srv/tcproxy completed..."
+    logsm "umount of all specified mount points completed."
 }
+
 
 stopping_VM() {
     if pgrep -f "mac=02:D2:46:5B:4E:84" >/dev/null 2>&1; then
